q_states:
  q_list:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
  initial: '0'
  final: '5'
alphabet:
  - a
  - b
tape_alphabet:
  - '#'
  - X
delta:
  # Procesar el primer símbolo desde el estado '0'
  - params:
      initial_state: '0'
      mem_cache_value: '#'
      tape_input: a
    output:
      final_state: '1'
      mem_cache_value: a
      tape_output: X
      tape_displacement: R
  - params:
      initial_state: '0'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '1'
      mem_cache_value: b
      tape_output: X
      tape_displacement: R
  # Avanzar por la cinta en estado '1'
  - params:
      initial_state: '1'
      mem_cache_value: '#'
      tape_input: a
    output:
      final_state: '1'
      mem_cache_value: a
      tape_output: a
      tape_displacement: R
  - params:
      initial_state: '1'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '1'
      mem_cache_value: b
      tape_output: b
      tape_displacement: R
  - params:
      initial_state: '1'
      mem_cache_value: '#'
      tape_input: X
    output:
      final_state: '1'
      mem_cache_value: X
      tape_output: X
      tape_displacement: R
  - params:
      initial_state: '1'
      mem_cache_value: '#'
      tape_input: '#'
    output:
      final_state: '2'
      mem_cache_value: '#'
      tape_output: '#'
      tape_displacement: L
  # Retroceder y procesar desde el estado '2'
  - params:
      initial_state: '2'
      mem_cache_value: '#'
      tape_input: a
    output:
      final_state: '3'
      mem_cache_value: a
      tape_output: X
      tape_displacement: L
  - params:
      initial_state: '2'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '3'
      mem_cache_value: b
      tape_output: X
      tape_displacement: L
  - params:
      initial_state: '2'
      mem_cache_value: '#'
      tape_input: X
    output:
      final_state: '2'
      mem_cache_value: X
      tape_output: X
      tape_displacement: L
  - params:
      initial_state: '2'
      mem_cache_value: '#'
      tape_input: '#'
    output:
      final_state: '5'
      mem_cache_value: '#'
      tape_output: '#'
      tape_displacement: N
  # Retroceder al inicio en estado '3'
  - params:
      initial_state: '3'
      mem_cache_value: '#'
      tape_input: a
    output:
      final_state: '3'
      mem_cache_value: a
      tape_output: a
      tape_displacement: L
  - params:
      initial_state: '3'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '3'
      mem_cache_value: b
      tape_output: b
      tape_displacement: L
  - params:
      initial_state: '3'
      mem_cache_value: '#'
      tape_input: X
    output:
      final_state: '0'
      mem_cache_value: X
      tape_output: X
      tape_displacement: R
  # Finalizar al encontrar únicamente '#' en la cinta
  - params:
      initial_state: '0'
      mem_cache_value: '#'
      tape_input: '#'
    output:
      final_state: '5'
      mem_cache_value: '#'
      tape_output: '#'
      tape_displacement: N
simulation_strings:
  - abbab
  - aaaab
  - babba
  - bbaaa
