q_states:
  q_list:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
  initial: '0'
  final: '5'
alphabet:
  - a
  - b
tape_alphabet:
  - '#'
  - X
delta:
  # Transición inicial para leer 'a'
  - params:
      initial_state: '0'
      mem_cache_value: '#'
      tape_input: a
    output:
      final_state: '1'
      mem_cache_value: a
      tape_output: a
      tape_displacement: R
  # Transición inicial para leer 'b'
  - params:
      initial_state: '0'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '1'
      mem_cache_value: b
      tape_output: b
      tape_displacement: R
  # Leer 'a' en el estado '1'
  - params:
      initial_state: '1'
      mem_cache_value: '#'
      tape_input: a
    output:
      final_state: '2'
      mem_cache_value: a
      tape_output: a
      tape_displacement: R
  # Leer 'b' en el estado '1'
  - params:
      initial_state: '1'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '2'
      mem_cache_value: b
      tape_output: b
      tape_displacement: R
  # Leer 'b' en el estado '2'
  - params:
      initial_state: '2'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '3'
      mem_cache_value: b
      tape_output: b
      tape_displacement: R
  # Leer '#' en el estado '2' para finalizar
  - params:
      initial_state: '2'
      mem_cache_value: '#'
      tape_input: '#'
    output:
      final_state: '5'
      mem_cache_value: '#'
      tape_output: '#'
      tape_displacement: R
  # Leer 'a' en el estado '3' para seguir procesando
  - params:
      initial_state: '3'
      mem_cache_value: '#'
      tape_input: a
    output:
      final_state: '3'
      mem_cache_value: a
      tape_output: a
      tape_displacement: R
  # Leer 'b' en el estado '3' para seguir procesando
  - params:
      initial_state: '3'
      mem_cache_value: '#'
      tape_input: b
    output:
      final_state: '3'
      mem_cache_value: b
      tape_output: b
      tape_displacement: R
  # Leer '#' en el estado '3' para finalizar
  - params:
      initial_state: '3'
      mem_cache_value: '#'
      tape_input: '#'
    output:
      final_state: '5'
      mem_cache_value: '#'
      tape_output: '#'
      tape_displacement: R
simulation_strings:
  - aab#aab
  - ab#ab
  - abbababa#aba
